{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Clean_Dataset\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.124.1052.0 (23.12)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-IN",
    "cultures": [
      {
        "name": "en-IN",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-IN",
    "tables": [
      {
        "name": "Clean_Dataset",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "airline",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ea282ced-67d7-4b74-b0c5-455ada869da0",
            "sourceColumn": "airline",
            "summarizeBy": "none"
          },
          {
            "name": "flight",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d284f31e-54f1-4099-9b20-418ef852ba6a",
            "sourceColumn": "flight",
            "summarizeBy": "none"
          },
          {
            "name": "source_city",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c8866e34-5eda-45d8-b7d0-b2ffab1551f8",
            "sourceColumn": "source_city",
            "summarizeBy": "none"
          },
          {
            "name": "departure_time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0054e25e-9dad-4a30-819c-9097b5d26752",
            "sourceColumn": "departure_time",
            "summarizeBy": "none"
          },
          {
            "name": "stops",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b56d9731-fc48-4b8a-ae7b-2399481b7e01",
            "sourceColumn": "stops",
            "summarizeBy": "none"
          },
          {
            "name": "arrival_time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8bb20710-0f95-40e8-93f4-f85cc08a1d98",
            "sourceColumn": "arrival_time",
            "summarizeBy": "none"
          },
          {
            "name": "destination_city",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "22f4d84b-51de-4277-a297-d9ebd2398186",
            "sourceColumn": "destination_city",
            "summarizeBy": "none"
          },
          {
            "name": "class",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "41c135ea-1158-40c0-85da-602c4e83bc14",
            "sourceColumn": "class",
            "summarizeBy": "none"
          },
          {
            "name": "duration",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "56acce1b-49f8-40f0-b596-11053d1d6e91",
            "sourceColumn": "duration",
            "summarizeBy": "sum"
          },
          {
            "name": "days_left",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "39293114-5be9-4b2e-bc4b-f1b7b2b44e06",
            "sourceColumn": "days_left",
            "summarizeBy": "sum"
          },
          {
            "name": "price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"as-IN\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "int64",
            "formatString": "\"₹\"\\ #,0.00;#,0.00\\ -\"₹\";\"₹\"\\ #,0.00",
            "lineageTag": "19fc0119-5a7b-4c75-ba39-4d81831958ba",
            "sourceColumn": "price",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "c5c851e9-60dd-40f6-a635-da3c62508507",
        "measures": [
          {
            "name": "TotalStops",
            "expression": "count(Clean_Dataset[stops])",
            "formatString": "0",
            "lineageTag": "42378323-65b3-41ae-80d3-cb3bad4f07a5"
          }
        ],
        "partitions": [
          {
            "name": "Clean_Dataset-94f77f77-df70-44c0-b7f7-3fd2370ab25b",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"D:\\B.TECH\\OTHERS\\Vraj seva\\Airline.xlsx\"), null, true),",
                "    Clean_Dataset_Sheet = Source{[Item=\"Clean_Dataset\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Clean_Dataset_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"airline\", type text}, {\"flight\", type any}, {\"source_city\", type text}, {\"departure_time\", type text}, {\"stops\", type text}, {\"arrival_time\", type text}, {\"destination_city\", type text}, {\"class\", type text}, {\"duration\", type number}, {\"days_left\", Int64.Type}, {\"price\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_ae282825-9649-4880-b322-77a2588b50b0",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "87acd421-bc25-4586-84db-1bddf87cea60",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "d558d050-f6ea-4e55-a184-19557757194d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "02a721a6-13fe-4156-bd81-63e740833073",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "6553d32a-8a88-4687-97fa-5fb9d1c3a98c",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "68f4c3be-7541-4139-811a-715bf0bebd84",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "25ac09d9-21bb-4629-bea4-a9a15fb038a8",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ba0f4245-1672-4caa-9ec4-36edf8c5334a",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "88fb96e0-47a5-4bc6-b0ed-bd131e43e56a",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "f9d07b96-1e22-4695-a842-06a27e76dcce",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "20524489-997c-433a-8fc0-007f18c0608b",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "972f8b27-517b-4c5f-b372-992104fcc213",
                "ordinal": 3
              }
            ],
            "lineageTag": "00ac6ed1-87e8-4ee7-99a0-7ac62e87032f"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "dd664e59-8e3a-44fd-a85a-2f7a4191393b",
        "partitions": [
          {
            "name": "DateTableTemplate_ae282825-9649-4880-b322-77a2588b50b0-da8860f8-61ec-4525-b7fa-c4ae3b541082",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}